### ISSUE TITLE
Items not showing in red book, star indicators not responding to breaking

### ISSUE THREAD

**Issue by SunflowerMead0w** [Bawnorton/RandoAssistant#23]
Hello, I love your mod, I have been playing it a lot recently. I am also new to writing bug reports, I hope I did a good job :)

**Expected Behavior**
Coral items:
After I have discovered and mined coral and coral fan items (not blocks, dead or alive, silk touched or not) the star indicators respond accordingly, when you search for how to find the thing it drops, it shows the pathway, and when you search for its name, you find what drops it. 

1.20 items + other plants:
After I have discovered and mined ^items, the star indicators respond accordingly. 

Searching for loot tables in the red book:
This is more of a suggestion than a bug report, but I would LOVE to see the ability to switch the direction of the search. So that, for instance, if I have a few stacks of an item in my hand with no stars on it and I don't know if I've gotten them incidentally or if I needed them for a resource I can look up what they drop without having to mine them.  Also/Or maybe have a page that will show loot table pathways of recently mined blocks. 
Also, can you please add an option to adjust the formatting of the loot table menu? It's great for things that only have one or two sources, but When I'm looking for the easiest way to get something that has many sources (like flower pots) this interface is completely unusable (see Screenshot 3). So being able to switch it to like a simple text based list view would be superb. Also being able to toggle whether certain options when searching (like toggle whether crafting or changing the state with a tool (stripping, deoxidizing, etc) shows up or not). Heck, even making the lines always go straight and use right angles instead of going directly to source like they do now. Or they could be different colors so it is easier to follow a path to it's origin. I don't know, just anything you can do here would be appreciated! 

**Actual Behaviour**
Coral items: 
The first two things do happen. Stars seem to be working, and if you know what it drops, when you search for it, it shows the pathway, but the pathway ends with the coral and it won't tell you what dropped it. When you search for it by name in the red book, nothing comes up. I know i've found it because I'm holding it in my hand, and the loot table says nothing. (Screenshot 1)

1.20 plants +...: 
Stars, especially silk touch stars, are either not responding, taking several tries, or don't respond until I quit and re-log, then the star will go away. Items I have noticed this happening with include hanging signs, pitcher plants, 2 block tall flowers, and hay bales. Logging out and in again and mining them several times has eliminated most of the stars, but pitcher plants simply will not recognize silk touch despite my having mined it with every tool type enchanted with silk touch I can think of.  (Screenshot 2)

Red book:
In general, I have noticed that the red book has a much harder time with following loot tables for items than it does with blocks. I wish I had more specific examples to give you here, but I honestly couldn't find any I'm sorry, my memory is a sieve. 

**Steps to Reproduce**

I am so sorry, I couldn't find the seed because I gave the folder a different name when I downloaded it, but here is the cheat sheet. 

[cheatsheet.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/11837610/cheatsheet.txt)

**What version of the mod are you using**

Most recent one as far as I'm aware. 

**Helpful Files**

Hope these work. I just used the snipping tool and then pasted in here. If they don't feel free to reach out to me on Discord (SunflowerMeadow#8024) and I can take and send new screenshots if you can't recreate them. 
Screenshot 1
![image](https://github.com/Benjamin-Norton/RandoAssistant/assets/137433815/dd2d5439-9f81-4bd0-b127-8c08386729c0)
Screenshot 2
![image](https://github.com/Benjamin-Norton/RandoAssistant/assets/137433815/59eaaf22-5919-4ad7-b465-79b7a1382d6e)
Screenshot 3
![image](https://github.com/Benjamin-Norton/RandoAssistant/assets/137433815/90da03d0-1ea7-4b84-bc8b-d7decff6d2dd)

- latest.log

[2023-06-21-2.log.gz](https://github.com/Benjamin-Norton/RandoAssistant/files/11837625/2023-06-21-2.log.gz)

**Comment by Benjamin-Norton** [comment]
Thanks for the report, it's well put together for a first issue. I'll look into this, the issue with tracking between items and blocks is sometimes they are not linked by anything other than the vanilla loot table, for example, the pitcher pod block according to the game doesn't have an item, and the pitcher pod plant item doesn't have a block. So logically you should expect the path to continue but it doesn't as the mod has lost track of which blocks are linked to which items. Same thing with flower pots, all pots with flowers in them are "flower pot blocks" but in reality each one is different. 

I'll see what I can do to improve the tracking of these types of items/blocks.

**Comment by SunflowerMead0w** [comment]
Thank you! And thanks for the super fast response, I wasn't expecting it.  If these things can't be resolved for some reason, that's fine, I can keep track of things ahead of time, I just need to know to do that first. I'm currently doing a challenge and am planning/hoping to do a video of a second attempt if the first was successful. (I'll credit/link you of course)

**Comment by Benjamin-Norton** [comment]
Keep this here to show my progress, as there are quite a few things to work on here.

Tasks:
- [ ] Match Non-Block Items to Blocks to resolve paths connecting and stars displaying properly
- [ ] Option to invert the search to search for what drops from x, rather that what drops x
- [ ] Option to toggle crafting/interactions in the graph
- [ ] Find a way to represent complex graphs so they're easier to use
   - May require re-writing of dynamic graph generator
   - 90° Angles might be the way to go
   - Colouring already exists (right click a node to show it's direct children)

**Comment by Benjamin-Norton** [comment]
Inverting the search is proving to be a lot more difficult than I had originally thought. I never designed the tracker to work both ways so it's taking me some time to do that one.

**Comment by Bawnorton** [comment]
Trulyrandom, my other mod based on this and a version that includes the tracker is available on GitHub (not published to cf yet) and address most of the concerns here. Search inversion is not planned due to limited use case and technical difficulties around the implementation in regards to performance.
