### ISSUE TITLE
[Bug Report] Game wont load on 1.20.2

### ISSUE THREAD

**Issue by Stxellxa** [Bawnorton/RandoAssistant#27]
Making a new instance of just Fabric API, the game still wont load with this mod, having tried past or recent Fabric API versions.

Using Prism Launcher, Java 17.0.9, Ubuntu 20.04
Fabric API 0.89.0 - 0.91.6

**What version of the mod are you using**
1.4.2
Minecraft 1.20.2

latest.log: (error starting from line 68)
[latest.log](https://github.com/user-attachments/files/15744394/latest.log)

**Comment by Bawnorton** [comment]
This mod is no longer being developed, its features are in the process of being merged into [TrulyRandom](https://github.com/Bawnorton/TrulyRandom) which targets 1.21

**Comment by Stxellxa** [comment]
alright, will look out for that :)

**Comment by Bawnorton** [comment]
https://github.com/Bawnorton/TrulyRandom/releases/tag/2.0.0-beta.1
