### ISSUE TITLE
[Bug Report] Game doesn't load on fabric 1.20.4

### ISSUE THREAD

**Issue by Bigfoot21801** [Bawnorton/RandoAssistant#28]
**Expected Behaviour**
Game should have loaded as normal and the mod should have been functioning as intended

**Actual Behaviour**
The came simply crashes before the Minecraft window even opens when using any version of the mod for 1.20 on fabric 1.20.4 even when the only other mod installed is fabric api.

**Steps to Reproduce**
- create a new fabric 1.20.4 profile using fabric installer, loader version is 0.15.11
- drag and drop any version of this mod for fabric 1.20 as well as the attached version of fabric api into the mods folder
- run the game through the default minecraft launcher

**What version of the mod are you using**
1.4.2, 1.4.1 or 1.4.0

**Helpful Files**
[fabric-api-0.97.1+1.20.4.zip](https://github.com/user-attachments/files/16593302/fabric-api-0.97.1%2B1.20.4.zip) -the version of fabric api used

- latest.log
[latest.log](https://github.com/user-attachments/files/16593321/latest.log)

-note: I very well could be a huge idiot, I only very recently started modding Minecraft without using an external launcher or mod loader like curseforge or modrinth. I also have not tested it with any other versions of Minecraft.

**Comment by Bawnorton** [comment]
This mod does not support 1.20.4 and is no longer maintained.
